Allow projects to load on SDK 10.0.15063 and update dependencies
PrismLibrary/Prism-Samples-Windows pull request #20
Opened 2017-05-04 20:40 UTC by ericwj

First step of #19.

Allow projects to load on SDK 10.0.15063 and update dependencies.

Also remove On***Changed which is obsoleted and to be replaced with Raise****Changed.

Temporarily add static methods that create DelegateCommands from a task async execute method. To be discussed how this is to be resolved going forward.

2017-05-30 23:24 UTC, brianlagunas requested changes
If you can make these changes I'll merge.

2017-05-30 23:24 UTC, brianlagunas commented on AdventureWorks.Shopper/AdventureWorks.UILogic/DelegateCommandHack.cs
> +    public class DelegateCommandHack
This isn't needed.  All commands can be updated to just 

```
SaveCommand = new DelegateCommand(async () => await SaveAsync);
```

2017-05-30 23:24 UTC, brianlagunas commented on AdventureWorks.Shopper/AdventureWorks.UILogic/ViewModels/ItemDetailPageViewModel.cs
> +                RaisePropertyChanged("IsBottomAppBarOpened");
we should use `RaisPropertyChanged(nameof(IsBottomAppBarOpened))`.  You can use find and replace for this. See this comment https://github.com/PrismLibrary/Prism/issues/1031#issuecomment-296704507

2017-07-11 20:30 UTC, brianlagunas approved these changes

2017-07-11 20:30 UTC, merged

2017-07-11 21:18 UTC, ericwj commented
Mmm how do I still amend this? It doesn't build.